const ERROR_CODES = {
    RATE_LIMITED: "RATE_LIMITED",
    INVALID_RECIPIENT: "INVALID_RECIPIENT",
    AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
    PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
    NETWORK_TIMEOUT: "NETWORK_TIMEOUT",
    UNKNOWN_PROVIDER_ERROR: "UNKNOWN_PROVIDER_ERROR",
    UNSUPPORTED_PROVIDER: "UNSUPPORTED_PROVIDER",
};

module.exports = ERROR_CODES;